Models/ErrorViewModel.cs
namespace midterm_project.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Pet.cs
using System.ComponentModel.DataAnnotations;

namespace midterm_project.Models;

public class Pet
{
    public int PetId { get; set; }
    [Required]
    [Display(Name = "Pet Name")]
    public string? PetName { get; set; }
    [Url]
    [Display(Name = "Pet Img URL")]
    public string? ImgUrl { get; set; }
    [Required]
    [Display(Name = "Pet Description")]
    public string? PetDescription { get; set; }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using midterm_project.Models;

namespace midterm_project.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PetController.cs
using midterm_project.Repositories;
using midterm_project.Models;
using Microsoft.AspNetCore.Mvc;


namespace midterm_project.Controllers;

public class PetController : Controller
{
    private readonly ILogger<PetController> _logger;
    private readonly IPetRepository _petRepository;

    public PetController(ILogger<PetController> logger, IPetRepository repository)
    {
        _logger = logger;
        _petRepository = repository;
    }

    public IActionResult List()
    {
        return View(_petRepository.GetAllPets());
    }
    [HttpGet]
    public IActionResult Detail(int id) 
    {
        var pet = _petRepository.GetPetById(id);

        if (pet == null) {
            return RedirectToAction("List");
        }

        return View(pet);
    }

    [HttpPost]
    public IActionResult Detail(Pet pet) 
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        
        _petRepository.UpdatePet(pet);
        
        return RedirectToAction("List");
    }

    [HttpGet]
    public IActionResult Add() 
    {
        return View();
    }

    [HttpPost]
    public IActionResult Add(Pet pet) 
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        
        _petRepository.CreatePet(pet);

        return RedirectToAction("List");
    }

    public IActionResult Delete(int id) 
    {
        _petRepository.DeletePetById(id);
        
        return RedirectToAction("List");
    }
}

Views/Home/Index.cshtml
@model IEnumerable<midterm_project.Models.Pet>
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="text-center">Pets For Adoption Website!</h1>
<div>
    <a class="btn btn-success mt-3" asp-controller="Pet" asp-action="List">View Pets!</a>
    <a class="btn btn-primary mt-3 float-end" asp-controller="Pet" asp-action="Add">Add New Pet!</a>
</div>

Views/Pet/Add.cshtml
@model midterm_project.Models.Pet

@{
    ViewData["Title"] = "Add Pet";
}

<form asp-controller="Pet" asp-action="Add" method="post">
    <h1 class="display-4 text-center mb-5">Add New Pet</h1>

    @await Html.PartialAsync("_PetInput", Model)

    <input type="submit" class="btn btn-sm btn-primary float-end" value="Save">
</form>

<a class="btn btn-sm btn-danger" asp-controller="Pet" asp-action="List">Back</a>

Views/Pet/Detail.cshtml
@model midterm_project.Models.Pet

@{
    ViewData["Title"] = "Pet Details";
}

<div class="resume-wrapper">
    <form asp-controller="Pet" asp-action="Detail" method="post">
        <h1 class="display-4 mb-5">Edit Pet</h1>

        @await Html.PartialAsync("_PetInput", Model)

        <input type="hidden" asp-for="PetId" />
        <div class="submit-wrapper">
            <input type="submit" class="btn btn-primary float-end" value="Save">
            <a class="btn btn-danger" asp-controller="Pet" asp-action="List">Back</a>
        </div>
    </form>
</div>

Views/Pet/List.cshtml
@model IEnumerable<midterm_project.Models.Pet>

@{
    ViewData["Title"] = "Home";
}

@* Can't get page to load *@

<div class="text-center">
    <h1 class="display-4">Pets for Adoption</h1>
    @foreach (var pet in Model)
    {
        <div class=pet-wrapper>
            <div class="left">
                <h3>@pet.PetName</h3>
                <p> @pet.PetDescription</p>
            </div>
            <div class="right">
               <div class="pix"> <img src="@pet.ImgUrl" /> </div>
                <div class="btns">
                    <a class="btn btn-sm btn-info mb-3" asp-controller="Pet" asp-action="Detail"
                        asp-route-id="@pet.PetId">
                         Edit Pet!
                    </a>
                    <a class="btn btn-sm btn-warning mb-3 ml-3" asp-controller="Pet" asp-action="SinglePet"
                        asp-route-id="@pet.PetId">
                         Pet Details!
                    </a>
                    <a class="btn btn-sm btn-danger mb-3 ml-3" asp-controller="Pet" asp-action="Delete"
                        asp-route-id="@pet.PetId">
                        Delete Pet
                    </a>
                </div>
            </div>
        </div>

    }


    <div>
        <a class="btn btn-primary mt-3 clearfix" asp-controller="Pet" asp-action="Add">Add New Pet!</a>
    </div>
</div>

Views/Pet/SinglePet.cshtml
@model IEnumerable<midterm_project.Models.Pet>
    

@{
    ViewData["Title"] = "Single";
}



<div class="text-center">
    <h1 class="display-4">Pets for Adoption</h1>

    <div class=pet-wrapper>
        <div class="left">
            <h3>PetName</h3>
            <p>PetDescription</p>
        </div>
        <div class="right">
            <div class="pix"> <img src="ImgUrl" /> </div>
            <div class="btns">
                <a class="btn btn-sm btn-info mb-3" asp-controller="Pet" asp-action="Detail" asp-route-id="PetId">
                    Edit Pet!
                </a>
                <a class="btn btn-warning" asp-controller="Pet" asp-action="List">Back</a>
            </div>
        </div>
    </div>


</div>

Views/Pet/_PetInput.cshtml
@model midterm_project.Models.Pet

<div class="form-group">
    <div class="row mb-4">
        <label class="control-label col-md-4" asp-for="PetName"></label>
        <input class="form-control col-md-8" asp-for="PetName" />
        <div class="col-10 offset-md-1 text-danger text-right">
            <span asp-validation-for="PetName"></span>
        </div>
    </div>

    <div class="row mb-4">
        <label class="control-label col-md-4" asp-for="ImgUrl"></label>
        <input class="form-control col-md-8" asp-for="ImgUrl" />
        <div class="col-10 offset-md-1 text-danger text-right">
            <span asp-validation-for="ImgUrl"></span>
        </div>
    </div>

    <div class="row mb-4">
        <label class="control-label col-md-4" asp-for="PetDescription"></label>
        <textarea class="form-control col-md-8" asp-for="PetDescription"></textarea>
        <div class="col-10 offset-md-1 text-danger text-right">
            <span asp-validation-for="PetDescription"></span>
        </div>
    </div>


</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - midterm_project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/midterm_project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">midterm_project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="List">Pets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - midterm_project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>